.github/workflows/cla.yaml
README.md

Added CLA bot workflow

---

README.md

Removes accidentally added duplicate installation instructions.

Remove duplicate installation instructions

---

src/mapper/pkg/resolvers/helpers.go
src/mapper/pkg/resolvers/resolver.go
src/mapper/pkg/resolvers/resolver_test.go

Intents holder is used in main, but its type is unexpected. Since it make set to handle it in main, this CR just change it type to exported.

Fix error: Exported function with unexported type

---

src/go.sum
src/mapper/cmd/main.go
src/mapper/pkg/graph/generated/generated.go
src/mapper/pkg/resolvers/resolver.go
src/mapper/pkg/resolvers/resolver_test.go

Recently the directory `network-mapper/src` was created but not all the generated files were re-generated accordingly. This PR update those files.

Update generated files with new path

---

.github/workflows/golangci-lint.yml
src/mapper.Dockerfile
src/mapper/pkg/clouduploader/cloud_upload.go
src/mapper/pkg/resolvers/resolver_test.go
src/shared/testbase/testsuitebase.go
src/sniffer.Dockerfile
src/sniffer/pkg/socketscanner/socketscanner.go

Add golangci-lint workflow

---

src/mapper/pkg/cloudclient/cloud_client.go
src/mapper/pkg/config/config.go

This PR fix configuration keys to align with other Otterize repos.

Fix api endpoint config name

---

src/mapper/pkg/cloudclient/cloud_client.go

Set API version to v1beta

---

.gitattributes
.gitmodules
src/go.mod
src/go.sum
src/mapper/pkg/cloudclient/generate.go
src/mapper/pkg/cloudclient/generated.go
src/mapper/pkg/cloudclient/genqlient.yaml
src/mapper/pkg/cloudclient/schema.graphql

Load graphql schema from staging server on go generate

Load graphql schema from staging server on go generate

---

README.md

Update otterize-cli version in installation instructions to v0.1.14

Update otterize-cli version in installation instructions to v0.1.14

---

src/go.mod
src/go.sum

Bump otterize cloudclient version to support custom root CAs when initializing cloud client.

Support custom root CAs when initializing cloud client

---

README.md

Update README with version bump

Update README with version bump

---

.github/workflows/release-tag.yaml

Add job to the release workflow that updates the helm-chart appVersion

Update helm chart on release

---

src/exp/istio-watcher/pkg/watcher/helpers.go
src/exp/istio-watcher/pkg/watcher/watcher.go
src/mapper/pkg/clouduploader/cloud_upload.go
src/mapper/pkg/clouduploader/models_to_api.go

Adding HTTP methods to Istio watcher among other small bug fixes.

Add HTTP methods to istio watcher

---

src/exp/istio-watcher/pkg/watcher/helpers.go

Fixing duplicate method reported by Istio watcher

Fixing duplicate method reported by Istio watcher

---

README.md

Add usage telemetry to README.md

Add usage telemetry to README.md

---

src/go.mod
src/go.sum

Following a bugfix in the telemetry sender package, updating it.
Relevant intents-operator PR: https://github.com/otterize/intents-operator/pull/177

Update telemetry sender package

---

.github/workflows/e2e-test.yaml

Don't send telemetry on tests.

Don't send telemetry on tests

---

.github/workflows/e2e-test.yaml
.github/workflows/tests-expected-results/simple-tutorial-intents.json
README.md

Mark CLI wget with test header on e2e test.

Mark CLI wget with test header on e2e test

---

.github/workflows/release-tag.yaml

Modify the version file on release. Pass version build_arg to the docker build&push actions.

Modify the version file on release

---

src/mapper/pkg/intentsstore/holder.go

This PR adds a debug log right after intents are recorded, to indicate that intents were successfully detected for this client.

Add debug log to indicate intents being added to intent store

---

.github/workflows/e2e-test.yaml

This PR fixes the e2e test for the main branch, broken by fixes to the fork build pipeline (oh the irony!).

Fix e2e test for main branch

---

src/go.mod
src/go.sum
src/mapper/cmd/main.go

Periodically send active component telemetry.

Periodically send active telemetry

---

src/mapper/cmd/main.go

This PR adds a missing Prometheus metrics HTTP handler to the mapper pod, which was already present in all other network mapper pods.

Add Prometheus metrics server to the mapper pod

---

src/mapper/pkg/clouduploader/cloud_uploader_test.go
src/mapper/pkg/clouduploader/intents_input_matcher.go

This PR doesn't add new functionality, only improve the tests infrastructure to support deep comparison of intents during tests and enable testing for typed discovered intents with resources.

Add test for discovered Kafka reporting

---

src/mapper/cmd/main.go
src/mapper/pkg/awsintentsholder/holder.go
src/mapper/pkg/cloudclient/cloud_client.go
src/mapper/pkg/clouduploader/cloud_upload.go
src/mapper/pkg/graph/generated/generated.go
src/mapper/pkg/graph/model/models_gen.go
src/mapper/pkg/resolvers/resolver.go
src/mapper/pkg/resolvers/resolver_test.go
src/mapper/pkg/resolvers/schema.resolvers.go
src/mappergraphql/schema.graphql

AWS Visibility is a new feature that expands the concept of discovered intents to all AWS operations. The Network mapper operator can receive and store reports of AWS operations executed in the cluster.

AWS discovered intents

---

.github/workflows/build.yaml

Builds modified IAMLive from an external repository, to include as part of network-mapper.

Build IAMLive

---

.github/workflows/release-tag.yaml

Publish IAMLive fork to dockerhub

Publish IAMLive on release

---

src/mapper/pkg/kubefinder/kubefinder.go
src/mapper/pkg/resolvers/schema.helpers.resolvers.go

Improve incoming internet intents detection to support of traffic to node port services

Support detection of incoming internet intents to NodePort services

---

build/kafka-watcher.Dockerfile
build/mapper.Dockerfile
build/sniffer.Dockerfile
src/go.mod
src/go.sum
src/mapper/cmd/main.go

Adding get cluster id call and bumping go version on dockerfile

Adding get cluster id call and bumping go version on dockerfile

---

src/mapper/pkg/resolvers/schema.helpers.resolvers.go

Change TCP log to trace

---

src/mapper/pkg/kubefinder/kubefinder.go

Leftover log from previous PR #210.

Change "no podCIDR" log to debug, since it does not indicate an error

---

src/go.mod
src/go.sum
src/mapper/pkg/kubefinder/kubefinder.go

Prior to this PR, these errors had the wrong or no stack.

Correctly initialize sentinel errors

---

src/mapper/pkg/kubefinder/kubefinder.go
src/mapper/pkg/resolvers/schema.helpers.resolvers.go

Prior to this PR, harmless errors would be erroneously reported in this case.

Don't report traffic when service has terminated

---

src/go.mod
src/go.sum
src/mapper/pkg/cloudclient/schema.graphql
src/mapper/pkg/resolvers/schema.helpers.resolvers.go

When usage telemetries are enabled, report TCP sniffing count telemetry.
[Docs update ](https://github.com/otterize/docs/pull/239)

Report TCP sniffing count telemetry

---

.github/workflows/lint.yml
.markdownlint.json
CODE_OF_CONDUCT.md
README.md
src/shared/testbase/README.md

This PR adds the [markdown-lint GitHub action](https://github.com/marketplace/actions/markdown-lint), checking for markdown issues in MD files. 
Additionally, this fixes any existing markdown issues. 
- https://github.com/marketplace/actions/markdown-lint

Add Markdown linter GitHub action and fix lint issues detected by it

---

src/mapper/pkg/resolvers/resolver_test.go
src/mapper/pkg/resolvers/schema.helpers.resolvers.go
src/shared/testbase/testsuitebase.go

Most CNI implementations ignore network policies targetting `hostNetwork` pods. We've decided to ignore them in the meantime.

Ignore target `hostNetwork` pods in the DNS capture flow

---

Makefile
build/agent.Dockerfile
build/bpfman.Dockerfile
dev/lima-k8s.yaml

Added a Makefile that automates installing Lima and managing image transfer between localhost and the kubernetes cluster inside the VM in order to automate local development.

Add makefile to automate local ebpf development

---

src/mapper/pkg/cloudclient/schema.graphql

Update Otterize Cloud GraphQL schema to latest version. 
[x]  This change adds test coverage for new/changed/fixed functionality
[x]  I have added documentation for new/changed functionality in this PR and in github.com/otterize/docs

Update Otterize Cloud GraphQL schema to latest version

---

.gitignore
Justfile
src/mapper/cmd/main.go
src/mapper/pkg/azureintentsholder/holder.go
src/mapper/pkg/cloudclient/generated.go
src/mapper/pkg/cloudclient/schema.graphql
src/mapper/pkg/clouduploader/cloud_upload.go
src/mapper/pkg/graph/generated/generated.go
src/mapper/pkg/graph/model/models_gen.go
src/mapper/pkg/graph/model/results_length.go
src/mapper/pkg/prometheus/metrics.go
src/mapper/pkg/resolvers/resolver.go
src/mapper/pkg/resolvers/resolver_test.go
src/mapper/pkg/resolvers/schema.helpers.resolvers.go
src/mapper/pkg/resolvers/schema.resolvers.go
src/mappergraphql/schema.graphql

Adds reporting of Azure actions, and translating them to discovered intents, as well as reporting them to cloud.

Report Azure discovered intents

---

src/mapper/pkg/cloudclient/generated.go
src/mapper/pkg/cloudclient/schema.graphql
src/mapper/pkg/clouduploader/cloud_upload.go
src/mapper/pkg/graph/generated/generated.go
src/mapper/pkg/graph/model/models_gen.go
src/mapper/pkg/kubefinder/kubefinder.go
src/mapper/pkg/resolvers/helpers.go
src/mapper/pkg/resolvers/schema.helpers.resolvers.go
src/mappergraphql/schema.graphql

Enhance discovered intents by including details on identity resolution methods. This information may become handy if a miss detection is found.

Enhance discovered intents by including details on identity resolution methods

---

src/mapper/pkg/dnscache/dns_cache.go
src/mapper/pkg/dnscache/dns_cache_test.go
src/mapper/pkg/dnsintentspublisher/dns_intents_publisher.go
src/mapper/pkg/resolvers/schema.helpers.resolvers.go

Adding support for wildcard prefix in DNS internet intents (*.example.com)### References

Adding support for wildcard prefix in DNS internet intents (*.example.com)

---

src/mapper/pkg/resolvers/schema.helpers.resolvers.go

Fixing panic caused by assignment happening before err check

Fixing panic caused by assignment happening before err check

---

.github/workflows/e2e-test.yaml
src/mapper/pkg/cloudclient/cloud_client.go
src/mapper/pkg/cloudclient/schema.graphql
src/mapper/pkg/graph/generated/generated.go
src/mapper/pkg/graph/model/models_gen.go
src/mapper/pkg/resolvers/helpers.go
src/mapper/pkg/resolvers/schema.helpers.resolvers.go
src/mappergraphql/schema.graphql

Adding Linkerd sidecar reporting to discovered intents resolution data

Adding Linkerd sidecar reporting to discovered intents resolution data

---

src/mapper/pkg/awsintentsholder/holder.go
src/mapper/pkg/cloudclient/generated.go
src/mapper/pkg/cloudclient/schema.graphql
src/mapper/pkg/clouduploader/cloud_upload.go
src/mapper/pkg/clouduploader/cloud_uploader_test.go
src/mapper/pkg/graph/generated/generated.go
src/mapper/pkg/graph/model/models_gen.go
src/mapper/pkg/resolvers/schema.helpers.resolvers.go
src/mapperclient/generated.go
src/mappergraphql/schema.graphql

Included iam role field in the reportAWSOperation resolver to allow us to map aws actions to specific roles in aws.

Add support for AWS role mapping

---

src/go.mod
src/go.sum
src/mapper/cmd/main.go

Related to: https://github.com/otterize/intents-operator/pull/573

Only use HTTP_PROXY/HTTPS_PROXY for outgoing traffic

---

src/mapper/cmd/main.go
src/mapper/pkg/cloudclient/schema.graphql
src/mapper/pkg/clouduploader/cloud_upload.go
src/mapper/pkg/dnscache/dns_cache_test.go
src/mapper/pkg/gcpintentsholder/holder.go
src/mapper/pkg/graph/generated/generated.go
src/mapper/pkg/graph/model/models_gen.go
src/mapper/pkg/graph/model/results_length.go
src/mapper/pkg/prometheus/metrics.go
src/mapper/pkg/resolvers/resolver.go
src/mapper/pkg/resolvers/resolver_test.go
src/mapper/pkg/resolvers/schema.helpers.resolvers.go
src/mapper/pkg/resolvers/schema.resolvers.go
src/mapperclient/client.go
src/mapperclient/generated.go
src/mapperclient/operations.graphql
src/mappergraphql/schema.graphql

Support for reports of GCP IAM visibility from the Otterize node-agent (eBPF agent).

Support for GCP IAM eBPF visibility

---

src/mapper/pkg/cloudclient/generated.go
src/mapper/pkg/cloudclient/schema.graphql
src/mapper/pkg/clouduploader/cloud_upload.go
src/mapper/pkg/clouduploader/cloud_uploader_test.go
src/mapper/pkg/concurrentconnectioncounter/connection_count_differ.go
src/mapper/pkg/concurrentconnectioncounter/connection_count_differ_test.go
src/mapper/pkg/concurrentconnectioncounter/countable_intent.go
src/mapper/pkg/externaltrafficholder/externaltrafficholder.go
src/mapper/pkg/incomingtrafficholder/incoming_traffic_holder.go
src/mapper/pkg/incomingtrafficholder/incoming_traffic_holder_test.go
src/mapper/pkg/intentsstore/holder.go
src/mapper/pkg/resolvers/schema.helpers.resolvers.go

Now we also report the connection count for incoming Internet connection (from outside the cluster to a workload inside the cluster).

Support reporting connection count for incoming Internet connections

---

src/mapper/pkg/metrics_collection_traffic/metrics_collection_traffic_handler.go
src/mapper/pkg/resourcevisibility/svc_reconciler.go
src/mapper/pkg/webhook_traffic/webhook_services_handler.go

In cases multiple reconcilers are sending the same data to cloud (for example, in the case of K8sWebhooks, we always send the state of the entire cluster) - we want to lock to make sure we won't send the same state multiple time to Otterzie cloud.
Reporting the state more than once would just make the cloud processing slower and deadlock.
Also include details of the environment this PR was developed in (language/platform/browser …

Improve performance - prevent sending the same state to Otterize cloud more than once
