otterize/network-mapper

- README.md
Go report badge now links to actual report instead of a static `A+` badge
> Go report badge now links to actual report

- src/mapper/cmd/main.go
- src/mapper/pkg/cloudclient/cloud_client.go
- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/cloudclient/genqlient.graphql
- src/mapper/pkg/cloudclient/genqlient.yaml
- src/mapper/pkg/cloudclient/mocks/mocks.go
- src/mapper/pkg/clouduploader/cloud_config.go
- src/mapper/pkg/clouduploader/cloud_upload.go
- src/mapper/pkg/clouduploader/cloud_uploader_test.go
- src/mapper/pkg/config/config.go
Replace environment id and source with namespace. EnvID is no longer used to identify the connection, and source is resolved in back end
> Report discovered intents by namespace

- src/mapper/pkg/cloudclient/cloud_client.go
- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/cloudclient/genqlient.graphql
- src/mapper/pkg/clouduploader/cloud_upload.go
- src/mapper/pkg/clouduploader/cloud_uploader_test.go
- src/mapper/pkg/clouduploader/intents_input_matcher.go
- src/mapper/pkg/resolvers/helpers.go
- src/mapper/pkg/resolvers/resolver_test.go
Until this PR client namespace wasn't sent to cloud, even though we always detect it. 
In addition, empty body was sent to cloud instead of nil due to annoying behavior of genqlient, who explicitly expect each nullable object to be decaled as, well, nullable 🤦‍♂️
This PR fix both problems while upgrading our testing so we can catch it in the future.
> Fix report discovered intents by namespace

- src/mapper/gqlgen.yml
- src/mappergraphql/.graphqlconfig.yaml
- src/mappergraphql/schema.graphql
Config file for each GraphQL project help IDE and other tools to differentiate between stand-along projects.
> Create config file for networkmapper grqphql

- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/clouduploader/cloud_uploader_test.go
- src/mapper/pkg/graph/generated/generated.go
Ran go generate to use new intents graphql schema without body & fixed tests.
> Run go generate with latest schema to fix null body error in intents reporting

- src/mapper/pkg/cloudclient/cloud_client.go
- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/cloudclient/genqlient.graphql
- src/mapper/pkg/cloudclient/genqlient.yaml
- src/mapper/pkg/cloudclient/mocks/mocks.go
- src/mapper/pkg/clouduploader/cloud_upload.go
- src/mapper/pkg/clouduploader/cloud_uploader_test.go
- src/mapper/pkg/clouduploader/intents_input_matcher.go
This PR update the report discovered intents implementation to the new API with the discovery time, but without sending the actual discovery value, just to be aligned with the new API.
> Add discovery time to discovered intents

- src/mapper/pkg/clouduploader/cloud_upload.go
Until this PR component status was sent only when interval time was done, this PR fix it to send connection status right when application is up.
> Send component status on start up

- src/go.mod
- src/mapper/cmd/main.go
- src/mapper/pkg/cloudclient/cloud_client.go
- src/mapper/pkg/clouduploader/cloud_config.go
- src/mapper/pkg/clouduploader/cloud_upload.go
- src/mapper/pkg/clouduploader/cloud_uploader_test.go
- src/mapper/pkg/kubefinder/kubefinder.go
- src/mapper/pkg/resolvers/schema.resolvers.go
This PR makes the network mapper use the shared cloud client from the intents-operator
Also fixes a small linter error
https://www.notion.so/otterize/Replace-mapper-cloud-client-with-shared-client-in-intents-operator-1ab83f28d41b40078506d041a4ef729e
> Using shared cloud client from intents-operator

- src/go.mod
- src/go.sum
- src/mapper/cmd/main.go
- src/mapper/pkg/cloudclient/cloud_client.go
- src/mapper/pkg/cloudclient/mocks/mocks.go
- src/mapper/pkg/clouduploader/cloud_config.go
- src/mapper/pkg/clouduploader/cloud_upload.go
- src/mapper/pkg/clouduploader/cloud_uploader_test.go
- src/mapper/pkg/resolvers/helpers.go
- src/mapper/pkg/resolvers/resolver.go
- src/mapper/pkg/resolvers/resolver_test.go
- src/mapper/pkg/resolvers/schema.resolvers.go
Previously, the network mapper would send to cloud the intents every time a new or existing intent was seen.
Now, it will only send the updated intents.
Also removed the persistency feature, at least temporarily, to simplify this change. The primary motivation behind the persistency feature was to simplify sending intents to the cloud.
> Only send new intents each time

- src/mapper/pkg/resolvers/schema.resolvers.go
Make sure we log every time ResetCapture mutation is called
> Add log print to ResetCapture

- src/mapper/pkg/cloudclient/schema.graphql
- src/mapper/pkg/resolvers/resolver_test.go
- src/mapper/pkg/resolvers/schema.resolvers.go
- src/mapper/pkg/resolvers/test_gql_client/generated.go
- src/mapper/pkg/resolvers/test_gql_client/genqlient.graphql
- src/shared/testbase/testsuitebase.go
As reported in issue https://github.com/otterize/network-mapper/issues/78, a bug caused the PodOwnerKind to return empty. The bug happened on services&intents discovered by the socket scan mechanism, due to a missing check of the pod owner. 
This PR fixes this issue and adds more checks to the tests to ensure it doesn't happen again.
Closes #78
> Fix for issue #78 - Fix missing pod owner info

- src/mapper/pkg/intentsstore/holder.go
When querying the old `serviceIntents` graphql endpoint, the network mapper may return some duplicate intents. This happens because the intents store may store different intent types over the same edge (which is OK), but the `serviceIntents` endpoint ignores intent types, and so it should deduplicate similar client+server pairs.
> Bugfix: network mapper returns duplicate intents on old service-intents endpoint

- src/exp/istio-watcher/mapperclient/generated.go
- src/exp/istio-watcher/pkg/watcher/helpers.go
- src/mapper/pkg/graph/generated/generated.go
- src/mapper/pkg/graph/model/models_gen.go
- src/mapper/pkg/resolvers/schema.resolvers.go
- src/mappergraphql/schema.graphql
GraphQL conversion bug fix.
Changed HTTP Resource schema to be a string for path (instead of array). Will now relay on mapper intent aggregation to join same src/dst connections.
> GraphQL conversion bug fix and aggregation changes

- src/exp/kafka-watcher/pkg/logwatcher/watcher.go
Previously, the Kafka watcher would follow logs, and if the connection was interrupted, it would fail to detect it and just hang forever. It now reads a small amount of logs at a time and continues from where it left off each time, with a short timeout to detect dead connections.
> Kafka watcher reads logs since last read, instead of following logs

- src/exp/istio-watcher/pkg/watcher/watcher.go
Envoy may set a request path to `unknown`. Those requests should be ignored. 
Note that we don't check if the path contains the work, since that would be a legitimate path, only if that's the actual value.
> Ignore unknown value in request path

- src/go.mod
- src/go.sum
Update intents-operator so the telemetries will be off by default. 
Because helm charts with latest tagged images are still out there, we will disable telemetry by default on the operator and keep it on from the helm-chart. By doing so, only new users will send telemetries while the old ones won't. https://github.com/otterize/intents-operator/pull/178
> Disable telemetry by default

- src/exp/istio-watcher/pkg/watcher/watcher.go
There are two issues with reading metrics from the servers envoy:
* clients may change their call to the server, the server sidecar will still contain the old logs
* there are some metrics where the client field is wrong, maybe due to a bug in Envoy workload resolution
This PR filter out only metrics where the sidecar is the source of the communication.
> Update envoy query to clients metrics only

- src/mapper/pkg/resolvers/resolver_test.go
- src/mapper/pkg/resolvers/schema.resolvers.go
- src/sniffer/pkg/config/config.go
This PR makes the mapper ignores results from deleted pods or pods that have been terminated. This is to mitigate a rare risk of inaccurate data being discovered in AWS. EKS may reuse IP addresses and when configuring the node group with more pods per node than recommended and rapidly deleting\creating pods the chances for reuse increase. 
We also ignore the result if the resolved Pod is terminated since controller-run time cache updates can be received in meaningful delay when cluster resources are exhausted. This means that a new communication seen only when the pod is terminated will be ignored, but it's important mitigation to avoid resolving inaccurate data.
This PR also increases the default timeout of sniffer reporting to make sure the mapper will receive the data even in …
> Validate that packet belongs to resolved pod by verifying timestamp

- .github/workflows/e2e-test.yaml
- src/sniffer/pkg/collectors/dnssniffer.go
- src/sniffer/pkg/ipresolver/process_monitor.go
- src/sniffer/pkg/ipresolver/process_montior_test.go
- src/sniffer/pkg/ipresolver/procfs_resolver.go
- src/sniffer/pkg/ipresolver/procfs_resolver_test.go
This solves an issue of the resolver not holding a mapping (ip:hostname) of a long lived process, just because on the first try (after process creation) we got "Permission Denied" on `/proc/$pid/environ`.
Turns out on process creation - there is some time where the process' dir already exists under `/proc` but not all files there are accessible yet.
The fix is to keep reporting the process as new (on the next intervals) as long as its handling wasn't successful (up to 3 retries).
This bug made the CI e2e tests flaky.
> [Bugfix] ProcFSIPResolver: Retry handling new processes if mapping extraction fails

- src/mapper/pkg/graph/generated/generated.go
- src/mapper/pkg/intentsstore/holder.go
- src/mapper/pkg/resolvers/schema.resolvers.go
- src/mappergraphql/schema.graphql
Adds a parameter in the network-mapper API to filter discovered intents by server. When using the serverName parameter in the Intents query, network-mapper will return all intents with that server as a destination, and all intents for the client of the  specified server.
> Filter discovered intents by server

- src/go.mod
- src/go.sum
- src/sniffer/pkg/collectors/socketscanner.go
- src/sniffer/pkg/collectors/socketscanner_test.go
Disables hostname validation check for socket scans. Also only regards sockets in state ESTABLISHED as open, to prevent misreporting connections. For example, connections can stay in TIME_WAIT for a relatively long time (30-60 sec) after being closed, resulting in reporting stale connections.
> Fix bug where socket scan hostname validation would erroneously discard socket scan data, and would treat non-ESTABLISHED connections as open

- src/go.mod
- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/cloudclient/schema.graphql
- src/mapper/pkg/graph/generated/generated.go
- src/mapper/pkg/graph/model/models_gen.go
- src/mapper/pkg/intentsstore/holder.go
- src/mapper/pkg/resolvers/resolver_test.go
- src/mapper/pkg/resolvers/schema.resolvers.go
- src/mapper/pkg/resolvers/test_gql_client/generated.go
- src/mapper/pkg/resolvers/test_gql_client/genqlient.graphql
- src/mappergraphql/schema.graphql
- src/sniffer/pkg/collectors/socketscanner_test.go
When filter intents by server we should get both server name and namespace, to make sure we get client intents from all namespaces who call this server. The namespace filter meant to filter for intents in an specific namespaces, it's not related and should be mutually exclusive with server name filter.
> Fix filter intents by server

- src/mapper/pkg/clouduploader/cloud_config.go
- src/mapper/pkg/clouduploader/cloud_upload.go
- src/mapper/pkg/clouduploader/cloud_uploader_test.go
- src/mapper/pkg/config/config.go
Following a bug related to the length of the discovered intents list, in order to future proof the process of reporting intents to the cloud, we would like to send intents to the cloud in batches.
> Report discovered intents to the cloud in batches

- src/mapper/pkg/clouduploader/cloud_uploader_test.go
The intents in the test are send in batches, but there is no guarantee that it will be sent in order. This is OK since the test only check the batch size, the order isn't important.
> Fix flaky test TestUploadIntentsInBatches

- .github/workflows/build-fork.yaml
- .github/workflows/e2e-test.yaml
- README.md
This PR fixes fork branch builds failing on the new end-to-end test, which was relying on the existence of a container registry to get the images between build steps. This PR now uses `actions/upload-artifact` and `actions/download-artifact` to achieve the same thing.
> Fixing fork e2e test

- src/kafka-watcher/pkg/config/config.go
The default Kafka log read mode was erroneously set to reading from file logs. This PR changes the default to Kubernetes log watching.
> Change default Kafka read mode to Kubernetes log watch

- src/kafka-watcher/pkg/logwatcher/filewatcher.go
- src/kafka-watcher/pkg/logwatcher/kubeneteslogwatcher.go
Until this PR the `kafka-cooldown-interval` argument was used to set the time between reports to the network mapper instead of `kafka-report-interval`. This PR change it to read the right configuration.
Since it's an infrastructural low level detail there is no test who check the interval. It can be reproduce by setting a value to report interval argument and checking time between reports in the logs.
There is no new functionality to document
> Fix bug: Cooldown interval config used instead of report interval

- src/graphql.config.yml
- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/cloudclient/graphql.config.yml
- src/mapper/pkg/cloudclient/schema.graphql
- src/mappergraphql/.graphqlconfig.yaml
- Replace old-style .graphqlconfig.yaml with new-style graphql.config.yml
- Place new graphql.config.yml file in global `src/` dir so that it can be used by all of the mapper schema clients
- Create a dedicated graphql.config.yml under cloudclient, referencing the schema for otterize cloud
- Update cloudclient schema.graphql & generated code
See https://the-guild.dev/graphql/config/docs/user/usage
> Add global graphql.config.yml file

- src/mapper/cmd/main.go
- src/mapper/pkg/cloudclient/cloud_client.go
- src/mapper/pkg/cloudclient/generate.go
- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/cloudclient/genqlient.graphql
- src/mapper/pkg/cloudclient/mocks/mocks.go
- src/mapper/pkg/cloudclient/schema.graphql
- src/mapper/pkg/clouduploader/cloud_upload.go
- src/mapper/pkg/clouduploader/cloud_uploader_test.go
- src/mapper/pkg/config/config.go
- src/mapper/pkg/externaltrafficholder/externaltrafficholder.go
- src/mapper/pkg/graph/generated/generated.go
- src/mapper/pkg/graph/model/models_gen.go
- src/mapper/pkg/intentsstore/holder.go
- src/mapper/pkg/metricexporter/metric_exporter.go
- src/mapper/pkg/metricexporter/metric_exporter_test.go
- src/mapper/pkg/resolvers/helpers.go
- src/mapper/pkg/resolvers/resolver.go
- src/mapper/pkg/resolvers/resolver_test.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
- src/mapper/pkg/resolvers/schema.resolvers.go
- src/mapper/pkg/resolvers/test_gql_client/generated.go
- src/mappergraphql/schema.graphql
- src/sniffer/pkg/collectors/collector.go
- src/sniffer/pkg/collectors/dnssniffer.go
- src/sniffer/pkg/collectors/dnssniffer_test.go
- src/sniffer/pkg/collectors/socketscanner.go
- src/sniffer/pkg/collectors/socketscanner_test.go
- src/sniffer/pkg/config/config.go
- src/sniffer/pkg/mapperclient/generated.go
This PR adds supporting for reporting internet-facing traffic. Up until now, the network mapper would see this traffic, but discard it. Now, the network mapper has gained the capability to report this traffic to Otterize Cloud. This will be used to display Internet traffic in the access graph, and in the future can be used for automatically bootstrapping Internet-facing intents, as well as matching traffic with services from other clusters, or managed databases, and so on.
> Support for reporting internet-facing traffic

- src/mapper/pkg/resolvers/helpers.go
- src/mapper/pkg/resolvers/resolver_test.go
- src/mapper/pkg/resolvers/schema.resolvers.go
- src/shared/testbase/testsuitebase.go
In some cases, empty source identities would be returned, causing erroneous reporting to Otterize Cloud. This PR fixes the problem and also adds regression tests.
> Fix bug where pod source identity could be incorrectly resolved

- src/sniffer/pkg/sniffer/sniffer.go
Previously, the network sniffer would not `return` once it logged an error for reporting to the mapper. This has no adverse effect, but the log that was produced was confusing, as it would log both an error and success:
```
{"error":"Post \"http://otterize-network-mapper:9090/query\": dial tcp 10.96.2.146:9090: i/o timeout","level":"error","msg":"Failed to report capture results","time":"2023-12-10T23:52:25Z"}                       │
{"level":"info","msg":"Reported captured requests of 1 clients to Mapper","time":"2023-12-10T23:52:25Z"}  
```
This PR fixes that.
> Fix bug where network sniffer would write a log indicating success reporting to mapper alongside log indicating failure

- src/mapper/cmd/main.go
- src/mapper/pkg/graph/model/results_length.go
- src/mapper/pkg/prometheus/metrics.go
- src/mapper/pkg/resolvers/helpers.go
- src/mapper/pkg/resolvers/resolver.go
- src/mapper/pkg/resolvers/resolver_test.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
- src/mapper/pkg/resolvers/schema.resolvers.go
Previous to the PR, network sniffers and the Istio and Kafka watchers would report their data to the network mapper, which would then handle them synchronously. The network mapper now buffers a limited amount of reports in-memory (using a channel), and rejects more reports when the channel is full. This enables the network mapper to absorb peaks in reports.
> Network mapper now buffers incoming reports instead of handling them synchronously, and collects statistics on loads and drops

- src/istio-watcher/cmd/main.go
- src/kafka-watcher/cmd/main.go
- src/mapper/cmd/main.go
- src/shared/componentutils/utils.go
- src/shared/config/config.go
- src/shared/kubeutils/kubeutils.go
- src/sniffer/cmd/main.go
Allow sharing the mapper context id with the other components who don't call directly to the control plane.
[Related Helm PR
](https://github.com/otterize/helm-charts/pull/146)
> Allow reporting errors with context id from sniffer and watchers

- src/mapper/cmd/main.go
The `echo` framework used for serving webhooks and metrics
did not use the context used in other parts of the mapper.
Thus, the process did not exit when a critical part of it
did not start properly, preventing a restart and error
reporting.
This commit shuts down echo cleanly when the main context is Done.
> Catch errors from all goroutines in network-mapper

- src/mapper/cmd/main.go
- src/mapper/pkg/dnsintentspublisher/init.go
- src/mapper/pkg/resolvers/resolver_test.go
This PR initialized the DNS publisher index before the manager start, since otherwise it cause panic.
> Fixed case where mapper could fail to initialize when domain name Internet intents were enabled

- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/cloudclient/schema.graphql
- src/mapper/pkg/graph/generated/generated.go
- src/mapper/pkg/graph/model/models_gen.go
- src/mapper/pkg/graph/model/results_length.go
- src/mapper/pkg/prometheus/metrics.go
- src/mapper/pkg/resolvers/resolver.go
- src/mapper/pkg/resolvers/resolver_test.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
- src/mapper/pkg/resolvers/schema.resolvers.go
- src/mapper/pkg/resolvers/test_gql_client/generated.go
- src/mapper/pkg/resolvers/test_gql_client/genqlient.graphql
- src/mappergraphql/schema.graphql
- src/shared/config/config.go
- src/sniffer/pkg/collectors/dnssniffer.go
- src/sniffer/pkg/collectors/socketscanner.go
- src/sniffer/pkg/collectors/tcpsniffer.go
- src/sniffer/pkg/collectors/tcpsniffer_test.go
- src/sniffer/pkg/ipresolver/ipresolver.go
- src/sniffer/pkg/mapperclient/client.go
- src/sniffer/pkg/mapperclient/generated.go
- src/sniffer/pkg/mapperclient/genqlient.graphql
- src/sniffer/pkg/mapperclient/mockclient/mocks.go
- src/sniffer/pkg/sniffer/sniffer.go
Add TCP-SYN packet sniffing to allow discovery of intents from pure TCP communication.
> Add TCP based intents discovery

- src/istio-watcher/pkg/watcher/watcher.go
Previously, we would try and get metrics even if there was no istio sidecar container.
> Skip pods with Istio label that still have no Istio sidecar injected

- src/istio-watcher/pkg/watcher/watcher.go
- src/kafka-watcher/pkg/logwatcher/kubeneteslogwatcher.go
Fix a case where the watchers (istio/kafka) tried to access logs of non-running pods
> Fix a case where the watchers (istio/kafka) tried to access logs of non-running pods

- build/kafka-watcher.Dockerfile
- build/mapper.Dockerfile
User $BUILDPLATFORM in build stage in Dockerfile: This will cause the builder image to be arm64 on Macs, and amd64 on CI and other environments.
Not cross-compiling arm64->amd64 on macs is significantly faster. The resulting images are without change.
https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/
> Use $BUILDPLATFORM in Dockerfile

- .github/workflows/build.yaml
Update the IAMLive repo path in CI. It pointed to the wrong github user. Since the repository was transferred, the old URL redirected to the correct one.
> Update iamlive repo url

- src/mapper/pkg/kubefinder/kubefinder.go
- src/mapper/pkg/resolvers/helpers.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
Prior to this PR, node PodCIDRs were always used to determine if an IP is considered external. However, sometimes the node CIDR can be unpopulated (or not populated yet?). Now we will treat those cases as if the IP is external, only checking the pod CIDRs if available, otherwise assuming that any pod not found means external traffic.
> Treat pod not found as external source traffic, only use node podCIDRs if possible.

- build/kafka-watcher.Dockerfile
- build/mapper.Dockerfile
- build/sniffer.Dockerfile
- src/kafka-watcher/cmd/main.go
- src/mapper/cmd/main.go
- src/sniffer/cmd/main.go
Depends on: https://github.com/otterize/intents-operator/pull/406
Now built using `-trimpath` so the stack traces are independent of build path.
> Upgrade error reporter version, fix cases where errors would not be reported or would be reported with wrong stack

- src/go.mod
- src/mapper/cmd/main.go
- src/mapper/pkg/config/config.go
- src/mapper/pkg/dnsintentspublisher/init.go
The mapper should by default update client intents with DNS resolution data to support intents to domain names server. It was only disabled by default until the full support of egress feature.
This PR also make the part where we check if `ClientIntents` CRD installed a little bit more clear & explicit. 
[The relevant Helm chart PR](https://github.com/otterize/helm-charts/pull/206)
There is no logic changes, and the CRD check can only be tested manually
> Enable DNS intents support by default

- src/go.mod
- src/mapper/pkg/config/config.go
- src/mapper/pkg/resourcevisibility/svc_reconciler.go
- src/mapper/pkg/resourcevisibility/svc_reconciler_test.go
Services may change in high frequency. This PR reduce the reporting level to once per minute (configurable) or based on meaningful changes to the services: deletion, change of resolved identity and type.
> Add cache to services reporting

- src/sniffer/pkg/collectors/dnssniffer.go
- src/sniffer/pkg/collectors/dnssniffer_test.go
When discovering intents to the internet, the mapper exports them using the CNAME as domain, instead of the actual domain name used. This PR check the CNAME section to get the domain name.
> Fix bug: internet intents discovered with CNAME instead of the actual domain name

- src/go.mod
- src/go.sum
- src/kafka-watcher/cmd/main.go
- src/mapper/cmd/main.go
- src/sniffer/cmd/main.go
After reconsidering Kubernetes custom resources versioning conventions, we have decided to upgrade `v1alpha3` to `v1beta1` instead of `v1`
https://github.com/otterize/intents-operator/pull/454/
> Update Otterize CRD versions following changes to the intents operator

- src/mapper/pkg/kubefinder/kubefinder.go
Since `hostNetwork` pods use the IP of their nodes, it doesn't make sense to use their IPs in this index.
> Fix a bug where a TCP connection to a `hostNetwork` pod could rarely be resolved to the wrong service

- .github/workflows/lint.yml
- src/mapper/pkg/kubefinder/kubefinder.go
- src/mapper/pkg/kubefinder/kubefinder_test.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
Improve the way we resolve services DNS to identities by going directly from the `targetRef` of `endpoints` instead of going through IP addresses
> Improve the way we resolve services DNS to identities by going directly from the `targetRef` of `endpoints` instead of going through IP addresses

- src/go.mod
- src/go.sum
Bump github.com/otterize/intents-operator/src dependency to latest main version.
> Bump intents-operator version to latest main

- src/kafka-watcher/cmd/main.go
- src/mapper/cmd/main.go
- src/sniffer/cmd/main.go
Use graphql enum type instead of string
> Fix error reporting - use the enum graphql type

- src/mapper/pkg/kubefinder/kubefinder.go
- src/mapper/pkg/resolvers/resolver_test.go
Ip addresses can be shared between multiple services if they use different ports. Until this PR we didn't support resolution in those cases
> Improve load balancer service resolution - support shared external ip address

- src/mapper/pkg/resolvers/helpers.go
- src/mapper/pkg/resolvers/resolver_test.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
Fix bug where traffic from a pod wasn't filtered properly by its creation timestamp. It happened because the filtering function didn't get a pointer - so the filter operation did not affect the calling scope.
> Fix bug where discovered traffic from a pod wasn't filtered properly by its creation timestamp

- src/mapper/pkg/kubefinder/kubefinder.go
- src/mapper/pkg/kubefinder/kubefinder_test.go
We fixed this bug by creating a TTL cache for pod IPs with an expiry time of 10 minutes.
> Fix a bug where detected TCP traffic from pods short time before their deletion time could be labeled as incoming traffic from the internet

- src/sniffer/cmd/main.go
> Handle case where the sniffer could fail to start if the metrics port was taken by another process on the same node, due to hostNetwork

- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/cloudclient/schema.graphql
Description
Update Otterize Cloud GraphQL schema to latest version.
Testing
[x] This change adds test coverage for new/changed/fixed functionality
Checklist
[x] I have added documentation for new/changed functionality in this PR and in github.com/otterize/docs
> Update GraphQL schema to latest version

- src/mapper/pkg/graph/generated/generated.go
- src/mapper/pkg/graph/model/models_gen.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
- src/mapperclient/generated.go
- src/mappergraphql/schema.graphql
ReportAWSOperation accepted a SrcIp parameter to link between a reported AWS operation and its pod. This has caused issues in cases where the source pod didn't exist by the time network-mapper received the report.
This PR adds a new parameter to the mutation, so that reporting clients can specify the service identity directly.
> Report AWS operations with service identity

- src/mapper/pkg/kubefinder/kubefinder.go
- src/mapper/pkg/resolvers/helpers.go
- src/mapper/pkg/resolvers/resolver_test.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
When running on minikube the control plane service is backed by a host networking pod. In this scenario, we should avoid using it as the source of discovered intents, because this communication we discover may be of another host networking pod.
> Fix a bug where host networking traffic could be misclassified as control plane traffic on Minikube

- src/sniffer/pkg/collectors/socketscanner.go
- src/sniffer/pkg/collectors/socketscanner_test.go
Send the listening port from the socket scanner to the mapper for additional debugging information
Changed tests for the socket scanner.
> Improve troubleshooting capabilities by sending the listening port of detected established connections from the sniffer to the mapper

- src/shared/config/config.go
- src/sniffer/cmd/main.go
Support configurable health server port for sniffer to prevent possible errors on startup 
Solving #260
> Support configurable health server port for sniffer to prevent possible errors on startup

- src/go.mod
- src/go.sum
- src/mapper/cmd/main.go
We have revamped the format for ClientIntents to make them easier to understand and make it possible to generate more restrictive policies by default. [Read more on the docs >>](https://docs.otterize.com/reference/ClientIntents%20CRD/migrateToV2)
The two primary changes is that the word `service` is no longer used, except to mean a Kubernetes Service; before, it could mean an Otterize Service or a Kubernetes Service, which was confusing. Instead, we now use `workload` . `calls` have also been renamed `targets` , and many smaller changes to the structure to improve
What happens to your existing ClientIntents? Don’t worry, the change is backwards compatible, and nothing changes unless you explicitly upgrade. If you’re a customer, we’ll reach out to explain and plan together. If you’re using …
> Support new API version for ClientIntents: v2beta1

- src/mapper/pkg/resolvers/resolver_test.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
**Problem**: Freshly started pods were not ignoring TCP SYN packets to their IPs, leading to unintended connections. In cases of rapid IP reuse, this caused excessive discovered intents, adding unnecessary noise.
**Solution**: TCP SYN packets to a pod are now ignored if the pod has been running for less than 5 minutes. This prevents premature connection handling during fast IP reuse scenarios
Also include details of the environment …
> Fix bug where TCP SYN to a pod IP was not ignored on freshly started pods, potentially causing spammed discovered intents in cases of fast IP reuse

- build/kafka-watcher.Dockerfile
- build/mapper.Dockerfile
- build/sniffer.Dockerfile
- src/mapper/cmd/main.go
- src/mapper/pkg/cloudclient/cloud_client.go
- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/cloudclient/genqlient.graphql
- src/mapper/pkg/cloudclient/mocks/mocks.go
- src/mapper/pkg/cloudclient/schema.graphql
- src/mapper/pkg/clouduploader/cloud_upload.go
- src/mapper/pkg/collectors/traffic/collector.go
- src/mapper/pkg/graph/generated/generated.go
- src/mapper/pkg/graph/model/models_gen.go
- src/mapper/pkg/graph/model/results_length.go
- src/mapper/pkg/resolvers/resolver.go
- src/mapper/pkg/resolvers/resolver_test.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
- src/mapper/pkg/resolvers/schema.resolvers.go
- src/mapperclient/client.go
- src/mapperclient/generated.go
- src/mapperclient/operations.graphql
- src/mappergraphql/schema.graphql
Aggregate data collected by the Otterize node-agent, using the traffic levels eBPF programs. This data includes the number of bytes, and number of connections between the services. The mapper then calculates a moving average, and reports it to the cloud.
> Collect traffic levels data from node-agent and upload to cloud

- src/mapper/pkg/resolvers/resolver.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
Initialized the GCP operations channel in resolvers (won't work without it). Also improved the logs in the area.
> Initialize the GCP operations channel in resolvers

- src/go.mod
- src/go.sum
Sometimes, the object's owner reference may be incorrect or not included in the schema. We don't want to fail in those situations; it is sufficient to halt owner resolution and report the error.
https://github.com/otterize/intents-operator/pull/578
> Fix bug where the workload identity resolution algorithm could fail if an owner ref uses a wrong apiVersion or kind

- src/mapper/pkg/clouduploader/cloud_upload.go
- src/mapper/pkg/collectors/traffic/collector.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
After enabling traffic levels, we encountered two issues:
1. The client or server name were sent as empty. If there had been an error resolving, the report should not have been sent at all, and error would be emitted. Added a specific check for this.
2. Reports are not being combined correctly - indexing by name and namespace only, not other fields in `ServiceIdentity`.
Also include details of the environment this PR was developed in …
> Fix issue where invalid traffic reports were reported to Otterize Cloud

- src/go.mod
- src/go.sum
Point to the latest version of intents operator
> Bugfix: point to the latest version of intents operator in go dependencies 

- .github/workflows/lint.yml
According to https://github.com/actions/runner-images/issues/11101, Ubuntu  20.04 LTS runner will be removed on 2025-04-15. This is currently failing CI
https://github.com/actions/runner-images/issues/11101
> Upgrade the runner machine for the golangci-lint CI step

- src/go.mod
- src/mapper/cmd/main.go
- src/mapper/pkg/cloudclient/cloud_client.go
- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/cloudclient/genqlient.graphql
- src/mapper/pkg/cloudclient/mocks/mocks.go
- src/mapper/pkg/cloudclient/schema.graphql
- src/mapper/pkg/networkpolicyreport/network_policies_reconciler.go
- src/mapper/pkg/networkpolicyreport/network_policy_reconciler_test.go
Enhance cloud network policy analysis by reporting the network policies to the cloud. This will enable Otterize to provide better insights regarding unused policies and blocked network traffic.
> Report network policies to the cloud for better insights on unused policies and blocked traffic

- src/mapper/pkg/networkpolicyreport/network_policies_reconciler.go
- src/mapper/pkg/networkpolicyreport/network_policy_reconciler_test.go
Fixed a bug where reporting network policies from a namespace without any policies could cause an error
> Fix bug where reporting network policies from a namespace without any policies could cause an error

- src/mapper/pkg/networkpolicyreport/cilium_clusterwide_policies_reconciler.go
- src/mapper/pkg/networkpolicyreport/cilium_clusterwide_policies_reconciler_test.go
- src/mapper/pkg/networkpolicyreport/helpers.go
- src/mapper/pkg/networkpolicyreport/network_policies_reconciler.go
- src/mapper/pkg/networkpolicyreport/network_policy_reconciler_test.go
Improve efficiency of network policies reporter by filtering large annotations before sending them to the cloud
> Improve efficiency of network policies reporter by filtering large annotations before sending them to the cloud

- src/mapper/pkg/config/config.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
Up until now, we did not report traffic when the source of this traffic was the control plane. After this fix, we will start report such traffic.
If you deploy older version of the network mapper, you would see that no traffic is being reported from the control plane to any other service.
To simulate such traffic, you can simple deploy `Otterize` on a cluster and apply client intent.
When you apply client intent, the control plane communicates with `intents-operator-webhook-server`.
> Report traffic originated from control plane

- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/cloudclient/schema.graphql
- src/mapper/pkg/clouduploader/cloud_uploader_test.go
- src/mapper/pkg/graph/generated/generated.go
- src/mapper/pkg/graph/model/models_gen.go
- src/mapper/pkg/intentsstore/holder.go
- src/mapper/pkg/resolvers/schema.helpers.resolvers.go
- src/mappergraphql/schema.graphql
Before this fix, we sometimes didn't resolve the destination properly, which result in dropping discovered intents in the mapper.
The cause of the error is that the sniffer sometimes pass on the destination the hostname of the workload it detects, and not the ip, while the mapper tries to resolve the destination assuming it is an ip address.
So in cases we do have the IP set from the sniffer - we want to use it to resolve the workload that is attached to the address.
Please include any manual steps for testing end-to-end or functionality not …
> Fixed bug where discovered intents were dropped in the mapper when collecting and parsing data from the sniffer

- src/mapper/pkg/intentsstore/holder.go
- src/mapper/pkg/metadatareporter/metadata_reporter.go
We had 2 different bugs that affected Kafka:
1. We did not reported the service IPs properly - thus failed to update the server data on Otterize cloud
2. We failed from reporting some of kafka intents to cloud
> Fixed bugs where kafka server metadata was not reported properly to cloud and another bug that dropped kafka intents from being reported

- .github/actions/e2e-test-setup-action/action.yaml
- .github/workflows/e2e-test.yaml
- .github/workflows/tests-expected-results/kafka-tutorial-intents.json
- .github/workflows/tests-expected-results/simple-tutorial-intents.json
> Added e2e test for kafka

- src/istio-watcher/pkg/watcher/watcher.go
Istio - changing metric collection from sidecar to include server source as well. This addresses missing HTTP methods & paths when reporting to Otterize cloud in a scenario where Istio's `VirtualService` and `Gateway` routing is involved.
> Istio - changing metric collection from sidecar to include server source as well

- src/mapper/pkg/metadatareporter/setup.go
Fix bug where indexes were used before being initialized by the metadataReporter. 
> Fix bug where indexes were used before being initialized by the metadataReporter

- src/mapper/pkg/kubefinder/kubefinder_test.go
- src/shared/testbase/testsuitebase.go
Fix test flakiness of TestIsSrcIpClusterInternal
https://github.com/otterize/network-mapper/actions/runs/15427866008/job/43419161728?pr=308
> Improve kubefinder tests stability

- src/mapper/pkg/cloudclient/generated.go
- src/mapper/pkg/cloudclient/schema.graphql
- src/mapper/pkg/resourcevisibility/model_convertion.go
- src/mapper/pkg/resourcevisibility/svc_reconciler.go
- src/mapper/pkg/resourcevisibility/svc_reconciler_test.go
Named ports are essential to understand if traffic is being allowed/blocked in cases where services or network polcies reference ports by their names
> Improve blocked traffic detection in Otterize Cloud by reporting container port names

- src/mapper/pkg/metrics_collection_traffic/metrics_collection_traffic_cache.go
- src/mapper/pkg/webhook_traffic/webhook_services_cache.go
Even though the data does not necessarily changes, we want to report it every once-in-a-while, to make sure we get the updated status on Otterize cloud
> Improve data accuracy in Otterize Cloud by periodically re-reporting data
